<a href="https://colab.research.google.com/github/JuanitaRozo/06-demo/blob/main/REDES_NEURONALES_B%C3%81SICAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**REDES NEURONALES BÁSICAS**
###**Redes Neuronales Básicas**

**Estudiante:** Nini Juanita Liberato Rozo

**Asignatura:** 608142/DEEP LEARNING -CONCEPTOS

**Docente:** NIDIA STELLA GARCIA ROA

**Fecha:** Septiembre de 2026

#**Objetivo**
Implementar desde cero distintos modelos básicos de redes neuronales en Python con NumPy, con el fin de entender cómo funciona el perceptrón, la red neuronal de una capa y la red neuronal multicapa.

#**Introducción**
El Machine Learning es una rama de la Inteligencia Artificial que desarrolla modelos que aprenden patrones de datos. La práctica que sigue tiene como objetivo el Deep Learning y la implementación de modelos neuronales sencillos en Python utilizando NumPy sin bibliotecas específicas. Se pretende entender cómo funcionan por dentro las redes neuronales mediante funciones de activación para hacer predicciones. Se construirá un perceptrón, una red neuronal con una capa y una multicapa.

#**Conceptos**
##**Machine Learning**
El Machine Learning o aprendizaje automático tiene como objetivo crear sistemas que sean capaces de aprender patrones a partir de datos. En vez de programar a mano todas las reglas necesarias para resolver un problema, un modelo de Machine Learning usa datos para encontrar relaciones y predecir cosas
##**Deep Learning**
El Deep Learning o aprendizaje profundo es un área del Machine Learning que emplea redes neuronales artificiales con múltiples capas.
Las redes profundas procesan la información de forma jerárquica, identificando distintas características y patrones en los datos.
Una diferencia importante es que una red neuronal con varias capas puede capturar relaciones más complejas que un modelo neuronal con una sola capa
##**Perceptron**
Es un clasificador lineal binario. Recibe múltiples señales numéricas de entrada, las procesa aplicando pesos y una función de activación, y produce una única salida binaria

salida= función de activación(X · W + b)
Donde:

X = Datos de entrada W = Pesos b = Sesgo

In [2]:
# Importación librería NumPy
import numpy as np

# Semilla aleatoria para garantizar los resultados reproducibles en cada ejecución
np.random.seed(42)

# Mensaje de confirmación y versión de NumPy
print("NumPy importado correctamente. Versión:", np.__version__)

NumPy importado correctamente. Versión: 2.1.3


##**Operacion con Numpy**

In [3]:
# Crear un vector
vector = np.array([1, 2, 3])

print("Vector:")
print(vector)

Vector:
[1 2 3]


In [4]:
# Crear una matriz
matriz = np.array([
    [1, 2],
     [3, 4]])

print("Matriz:")
print(matriz)

Matriz:
[[1 2]
 [3 4]]


##**Multipicacion Matricial**

In [5]:
# Crear un segundo vector
vector_2 = np.array([5, 6])

# Realizar el producto matricial
resultado = np.dot(matriz, vector_2)

print("Resultado del producto matricial:")
print(resultado)

Resultado del producto matricial:
[17 39]


#El Perceptrón Compuerta Lógica AND
Se programa la arquitectura básica de una neurona artificial para aprender la compuerta lógica AND


In [6]:
# Define la matriz de entradas (4 combinaciones de 2 entradas)
A= np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define el vector de salidas esperadaS B
B= np.array([0, 0, 0, 1])

# Función de activación escalón
# 1 si el valor es mayor o igual a 0 O de lo contrario 0
def funcion_escalon(z):
    return np.where(z >= 0, 1, 0)

# Definición de la clase Perceptron para emular el aprendizaje iterativo
class Perceptron:
    def __init__(self, input_dim, lr=0.1, epochs=10):
        self.weights = np.zeros(input_dim) # Inicializa los pesos sinápticos en ceros
        self.bias = 0.0 # Inicializa el sesgo en cero
        self.lr = lr # Tasa de aprendizaje
        self.epochs = epochs # Número de épocas

    def entrenar(self, A, B):
        # Bucle externo que repite el proceso de aprendizaje por el número de épocas definido
        for epoch in range(self.epochs):
            # Itera simultáneamente sobre cada par de entrada y su salida esperada
            for xi, target in zip(A, B):
                # Obtiene la predicción del perceptrón para entrada xi
                prediccion = self.predecir(xi)
                actualizacion = self.lr * (target - prediccion) # Calcula el término de actualización basado en el error
                self.weights += actualizacion * xi # Actualiza los pesos suma el producto de la actualización y los valores de entrada
                self.bias += actualizacion # actualizacion de sesgo

    def predecir(self, x):
        #Producto punto entre la entrada y los pesos suma el sesgo (z = W*X + b)
        z = np.dot(x, self.weights) + self.bias
        # Aplicación de función escalonada para convertir la salida lineal en una predicción binaria
        return funcion_escalon(z)

# Se crea una instancia del Perceptor configurada para recibir 2 características de entrada
perceptron = Perceptron(input_dim=2)

# Ejecuta el método de entrenamiento con los datos de la compuerta AND
perceptron.entrenar(A, B)

# Muestra los resultados obtenidos después de entrenar el perceptrón
print("Resultados del Perceptrón (AND):")
for xi in A:
    # Muestra la entrada evaluada junto con la predicción generada por el perceptrón
    print(f"Entrada: {xi} -> Predicción: {perceptron.predecir(xi)}")

Resultados del Perceptrón (AND):
Entrada: [0 0] -> Predicción: 0
Entrada: [0 1] -> Predicción: 0
Entrada: [1 0] -> Predicción: 0
Entrada: [1 1] -> Predicción: 1


##**Red Neuronal de Una Capa**

Implementación de una red de una capa que utiliza la función de activación sigmoide y el algoritmo de descenso de gradiente para resolver problemas de clasificación lineal aqui trabajaremos con varias entradas y varias neuronas de salida mediante matrices

In [7]:
def sigmoide(z):
    # Utilizo np.clip para evitar desbordamientos numéricos por valores muy grandes o pequeños
    return 1 / (1 + np.exp(-np.clip(z, -500, 500)))

# Derivada sigmoide utilizada para calcular los gradientes durante la retropropagación
def derivada_sigmoide(s):
    return s * (1 - s)

# Datos de entrada para una compuerta OR
X_or = np.array([[0, 0],
                 [0, 1],
                 [1, 0],
                 [1, 1]])

# Salidas esperadas
y_or = np.array([[0], [1], [1], [1]])

# Inicializa aleatoriamente los pesos de la capa con una matriz 2x1
W = np.random.randn(2, 1)

# Inicializa el sesgo como una matriz de ceros
b = np.zeros((1, 1))

# Tasa de aprendizaje
lr = 0.5

for epoca in range(10000):
    # Propagación hacia adelante calcula la combinación lineal (z = X*W + b)
    z = np.dot(X_or, W) + b

    # Eesultado lineal a través de la función sigmoide (predicciones continuas)
    predicciones = sigmoide(z)

    error = y_or - predicciones

    gradiente = error * derivada_sigmoide(predicciones)

    # Actualiza los pesos sumando el producto punto de la matriz de entrada transpuesta por el gradiente
    W += lr * np.dot(X_or.T, gradiente)

    # Actualiza el sesgo sumando los valores del gradiente a lo largo de las filas, manteniendo las dimensiones
    b += lr * np.sum(gradiente, axis=0, keepdims=True)

print("Resultados Red Neuronal de Una Capa:")
print(np.round(predicciones))

Resultados Red Neuronal de Una Capa:
[[0.]
 [1.]
 [1.]
 [1.]]


##**Red Neuronal Multicapa**

Implementación desde cero de una red neuronal multicapa capaz de resolver problemas no linealmente separables como la compuerta lógica XOR

In [11]:
# Define los datos de entrada para la compuerta XOR (problema no linealmente separable)
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Define las salidas deseadas para la compuerta XOR
y_xor = np.array([[0], [1], [1], [0]])

input_size = 2    # de neuronas de entrada (características)
hidden_size = 2   # de neuronas en la capa oculta
output_size = 1   # de neuronas en la capa de salida

# Inicializa aleatoriamente los pesos de la entrada a capa oculta
W1 = np.random.randn(input_size, hidden_size)

# Inicializa los sesgos de la capa oculta en ceros
b1 = np.zeros((1, hidden_size))

# Inicializa aleatoriamente los pesos de la capa oculta a salida
W2 = np.random.randn(hidden_size, output_size)

# Inicializa el sesgo de la capa de salida en cero
b2 = np.zeros((1, output_size))

# Tasa de aprendizaje para velocidad y estabilidad del ajuste
lr = 0.5

epocas = 20000

for epoca in range(epocas):

    # 1. Propagación hacia adelante
    # Combinación lineal para la capa oculta X * W1 + b1
    z_oculto = np.dot(X_xor, W1) + b1

    # Función sigmoide para activaciones de la capa oculta
    a_oculto = sigmoide(z_oculto)

    # Calcula la combinación lineal para la capa de salida usando las activaciones ocultas a_oculto * W2 + b2
    z_salida = np.dot(a_oculto, W2) + b2

    predicciones = sigmoide(z_salida)

    # 2. Retropropagación
    # Calcula el error en la capa de salida
    error_output = y_xor - predicciones

    # Calcula el término delta (gradiente) para la capa de salida
    d_salida = error_output * derivada_sigmoide(predicciones)

    # Propaga el error hacia la capa oculta multiplicando el delta de salida por la matriz de pesos W2 transpuesta
    error_hidden = np.dot(d_salida, W2.T)

    # Calcula el término delta (gradiente) para la capa oculta utilizando su derivada
    d_oculto = error_hidden * derivada_sigmoide(a_oculto)

    # 3. Actualización de Parámetros de la Red
    # Actualiza los pesos de la capa de salida W2 usando la regla del gradiente descendente
    W2 += lr * np.dot(a_oculto.T, d_salida)

    # Actualiza los sesgos de la capa de salida (b2) sumando los gradientes
    b2 += lr * np.sum(d_salida, axis=0, keepdims=True)

    # Actualiza los pesos de la primera capa W1 usando las entradas y el delta oculto
    W1 += lr * np.dot(X_xor.T, d_oculto)

    # Actualiza los sesgos de la capa oculta b1 sumando los gradientes
    b1 += lr * np.sum(d_oculto, axis=0, keepdims=True)

# Muestra los resultados finales obtenidos por la red multicapa al resolver XOR
print("Resultados Red Multicapa (XOR):")
for i in range(len(X_xor)):
    print(f"Entrada: {X_xor[i]} -> Predicción real: {predicciones[i][0]:.4f} -> Redondeado: {np.round(predicciones[i][0])}")

Resultados Red Multicapa (XOR):
Entrada: [0 0] -> Predicción real: 0.0108 -> Redondeado: 0.0
Entrada: [0 1] -> Predicción real: 0.9862 -> Redondeado: 1.0
Entrada: [1 0] -> Predicción real: 0.4998 -> Redondeado: 0.0
Entrada: [1 1] -> Predicción real: 0.5003 -> Redondeado: 1.0


##**Conclusión**
La práctica nos permitió comprender el funcionamiento básico de una red neuronal artificial, incluyendo el procesamiento de datos por un perceptrón mediante pesos y sesgo, así como la operación de una función de activación para hacer predicciones, se aprendió a calcular el error para ajustar los pesos en el entrenamiento y usamos NumPy para el manejo de vectores y matrices, que facilitan los cálculos necesarios